spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <client-id>
            client-secret: <client-secret>
  data:
    cassandra:
      keyspace-name: main
      username: <client-id-from-datastax-hosted-instance>
      password: <client-secret-from-datastax-hosted-instance>
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

#connecting to a hosted cassandra instance
astra.db:
  id: <data-center-id-from-datastax-hosted-instance>
  region: us-east1
  keyspace: main
  application.token: <access-token-from-datastax-hosted-instance>

#securely connecting to astra hosted cassandra instance
datastax.astra:
  secure-connect-bundle: secure-connect-better-reads.zip